[package]
name = "pms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
prost = { version = "0.13.4", default-features = false, features = ["prost-derive"] }
thiserror = "2.0.11"
pty-process = { version = "0.5.1", features = ["default", "tokio", "async"] }
tracing-subscriber = { version = "0.3.19", features = ["json"] }
tracing = "0.1.41"
crossterm = { version = "0.28.1", features = ["libc"] }
byteorder = "1.5.0"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
signal-hook = "0.3.17"
futures-util = "0.3.30"

[dev-dependencies]
rand = "0.9.0"
serial_test = "3.1.1"

[build-dependencies]
prost-build = "0.13.4"